# Generated by Django 5.0.4 on 2024-05-11 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_order_orderitem_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='shipping_address',
        ),
    ]
