# Generated by Django 5.0.6 on 2024-05-20 13:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_myuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Salad', 'Salad'), ('Chips', 'Chips'), ('Drinks', 'Drinks'), ('Merchandise', 'Merchandise')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
